---
apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: test-pod
spec:
  containers:
  - name: liveness
    image: iamshubhamvaidya520/my-images:health-check
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthz; sleep 300
    ports:
    - containerPort: 8080
    # livenessProbe:
    #   httpGet:
    #     path: /tmp/healthz
    #     port: 8080
    #   initialDelaySeconds: 3
    #   periodSeconds: 3
    # readinessProbe:
    #   httpGet:
    #     path: /tmp/healthz
    #     port: 8080
    #   initialDelaySeconds: 15
    #   periodSeconds: 10