---
apiVersion: v1
kind: Pod
metadata:
  labels:
    test: liveness
  name: test-pod
spec:
  containers:
  - name: liveness
    image: iamshubhamvaidya520/my-images:health-check
    ports:
    - containerPort: 8080
    livenessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 3
      periodSeconds: 3
    readinessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 15
      periodSeconds: 10