---
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod-load-cm
  labels:
    app.kubernetes.io/name: MyApp
spec:
  containers:
  - name: myapp-container
    image: busybox:1.28
    envFrom:
    - secretRef:
        name: test-secret
    command: ['sh', '-c', 'echo The app is running! && sleep 3600']