apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc
  labels:
    env: nginx-app
spec:
  template:
    metadata:
      name: ngnix-app
      labels:
        env: test
        app: my-app
    spec:
      containers:
        - name: ngnix-container
          image: nginx:latest
          ports:
            - containerPort: 80
  replicas: 3