apiVersion: v1
kind: Pod
metadata:
  name: ngnix-pod1
  labels:
    env: test
    app: my-app
spec:
  containers:
    - name: ngnix-container
      image: nginx:latest
      ports:
        - containerPort: 80